from typing import Any, Generic, TypeVar

from django.db.models.manager import Manager as Manager
from django.db.models.query import (
    Prefetch as Prefetch,
    QuerySet as QuerySet,
    aprefetch_related_objects as aprefetch_related_objects,
    prefetch_related_objects as prefetch_related_objects,
)

_T = TypeVar("_T")

CASCADE: Any
DO_NOTHING: Any
PROTECT: Any
RESTRICT: Any
SET: Any
SET_DEFAULT: Any
SET_NULL: Any


class Model:
    id: int
    pk: int

    def __init__(self, **kwargs: Any) -> None: ...


class Field(Generic[_T]):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...


class AutoField(Field[int]): ...
class BigAutoField(Field[int]): ...
class SmallAutoField(Field[int]): ...
class IntegerField(Field[int]): ...
class BigIntegerField(Field[int]): ...
class SmallIntegerField(Field[int]): ...
class PositiveIntegerField(Field[int]): ...
class PositiveSmallIntegerField(Field[int]): ...
class PositiveBigIntegerField(Field[int]): ...
class BooleanField(Field[bool]): ...
class FloatField(Field[float]): ...
class DecimalField(Field[Any]): ...
class CharField(Field[str]): ...
class TextField(Field[str]): ...
class SlugField(Field[str]): ...
class EmailField(Field[str]): ...
class URLField(Field[str]): ...
class FilePathField(Field[str]): ...
class GenericIPAddressField(Field[str]): ...
class UUIDField(Field[Any]): ...
class BinaryField(Field[bytes]): ...
class DateField(Field[Any]): ...
class DateTimeField(Field[Any]): ...
class TimeField(Field[Any]): ...
class DurationField(Field[Any]): ...
class JSONField(Field[object]): ...
class FileField(Field[Any]): ...
class ImageField(Field[Any]): ...


class ForeignKey(Field[Any]):
    def __init__(self, to: Any, on_delete: Any, *args: Any, **kwargs: Any) -> None: ...


class ForeignObject(ForeignKey): ...


class OneToOneField(ForeignKey): ...


class ManyToManyField(Field[Any]):
    def __init__(self, to: Any, *args: Any, **kwargs: Any) -> None: ...


class ForeignObjectRel: ...
class ManyToOneRel: ...
class ManyToManyRel: ...
class OneToOneRel: ...


class Q: ...
class FilteredRelation: ...
class Lookup: ...
class Transform: ...
class ObjectDoesNotExist(Exception): ...
