from typing import Any, Generic, TypeVar

from django.db.models.query import QuerySet

_T = TypeVar("_T")


class BaseManager(Generic[_T]):
    def all(self) -> QuerySet[_T, _T]: ...
    def filter(self, *args: Any, **kwargs: Any) -> QuerySet[_T, _T]: ...
    def exclude(self, *args: Any, **kwargs: Any) -> QuerySet[_T, _T]: ...
    def complex_filter(self, filter_obj: Any) -> QuerySet[_T, _T]: ...
    def get(self, *args: Any, **kwargs: Any) -> _T: ...
    def create(self, **kwargs: Any) -> _T: ...
    def get_or_create(self, defaults: dict[str, Any] | None = None, **kwargs: Any) -> tuple[_T, bool]: ...
    def update_or_create(self, defaults: dict[str, Any] | None = None, create_defaults: dict[str, Any] | None = None, **kwargs: Any) -> tuple[_T, bool]: ...
    def first(self) -> _T | None: ...
    def last(self) -> _T | None: ...
    def earliest(self, *fields: str) -> _T: ...
    def latest(self, *fields: str) -> _T: ...
    def count(self) -> int: ...
    def exists(self) -> bool: ...
    def values(self, *fields: str, **expressions: Any) -> QuerySet[_T, dict[str, object]]: ...
    def values_list(self, *fields: str, flat: bool = False, named: bool = False) -> QuerySet[_T, object]: ...
    def annotate(self, *args: Any, **kwargs: Any) -> QuerySet[_T, _T]: ...
    def alias(self, *args: Any, **kwargs: Any) -> QuerySet[_T, _T]: ...
    def order_by(self, *field_names: str) -> QuerySet[_T, _T]: ...
    def distinct(self, *field_names: str) -> QuerySet[_T, _T]: ...
    def none(self) -> QuerySet[_T, _T]: ...
    def only(self, *fields: str) -> QuerySet[_T, _T]: ...
    def defer(self, *fields: str) -> QuerySet[_T, _T]: ...
    def select_related(self, *fields: str | None) -> QuerySet[_T, _T]: ...
    def prefetch_related(self, *lookups: str) -> QuerySet[_T, _T]: ...
    def select_for_update(self, **kwargs: Any) -> QuerySet[_T, _T]: ...
    def reverse(self) -> QuerySet[_T, _T]: ...
    def using(self, alias: str | None) -> QuerySet[_T, _T]: ...
    def union(self, *other_qs: QuerySet[_T, Any], all: bool = False) -> QuerySet[_T, _T]: ...
    def intersection(self, *other_qs: QuerySet[_T, Any]) -> QuerySet[_T, _T]: ...
    def difference(self, *other_qs: QuerySet[_T, Any]) -> QuerySet[_T, _T]: ...
    async def aget(self, *args: Any, **kwargs: Any) -> _T: ...
    async def acreate(self, **kwargs: Any) -> _T: ...
    async def aget_or_create(self, defaults: dict[str, Any] | None = None, **kwargs: Any) -> tuple[_T, bool]: ...
    async def aupdate_or_create(self, defaults: dict[str, Any] | None = None, create_defaults: dict[str, Any] | None = None, **kwargs: Any) -> tuple[_T, bool]: ...
    async def afirst(self) -> _T | None: ...
    async def alast(self) -> _T | None: ...
    async def acount(self) -> int: ...
    async def aexists(self) -> bool: ...


class Manager(BaseManager[_T], Generic[_T]): ...


class EmptyManager(Manager[_T], Generic[_T]): ...


class ManagerDescriptor:
    manager: BaseManager[Any]
