[mypy]
plugins = mypy_django_plugin.main
strict = true
incremental = false
pretty = false
show_column_numbers = true
show_error_codes = true
warn_unreachable = true

[mypy.plugins.django-stubs]
django_settings_module = conformance_project.settings
